// ------------------------------------------------------------------------------
//  <auto-generated>
//      Este código lo generó el generador de pruebas de IU codificadas.
//      Versión: 14.0.0.0
//
//      Los cambios realizados en este archivo pueden provocar un comportamiento incorrecto y se perderán si
//      se vuelve a generar el código.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace AnularCancelarOrdenCompra
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// SeleccionarOrdendecomprayAnularlaCancelaciondecomprobante - Caso de prueba 309
        /// </summary>
        public void SeleccionarOrdendecomprayAnularlaCancelaciondecomprobante()
        {
            #region Variable Declarations
            WinButton uICOMPRASButton = this.UIFlexBusinessERP41HUAWindow.UIExplorerBarWindow.UICOMPRASButton;
            WinTreeItem uIOrdenesdecompraAprobTreeItem = this.UIFlexBusinessERP41HUAWindow.UIItemWindow.UIItemTree.UIOperacionesTreeItem.UIOrdenesdecompraTreeItem.UIOrdenesdecompraAprobTreeItem;
            WinListItem uIItem0050009007ListItem = this.UIFlexBusinessERP41HUAWindow.UIOrdenesdecompraAprobWindow.UILvItemsList.UIItem0050009007ListItem;
            WinButton uIAnularlacancelacióndButton = this.UIFlexBusinessERP41HUAWindow.UI_frmMain_Toolbars_DoToolBar.UIAnularlacancelacióndButton;
            #endregion

            // Clic 'COMPRAS' botón
            Mouse.Click(uICOMPRASButton, new Point(65, 13));

            // Clic 'Operaciones' -> 'Ordenes de compra' -> 'Ordenes de compra - Aprobadas' elemento de árbol
            Mouse.Click(uIOrdenesdecompraAprobTreeItem, new Point(80, 16));

            // Clic '005-0009007' elemento de lista
            Mouse.Click(uIItem0050009007ListItem, new Point(74, 8));

            // Clic 'Anular la cancelación de comprobante' botón
            Mouse.Click(uIAnularlacancelacióndButton, new Point(16, 9));
        }
        
        /// <summary>
        /// Aceptar - Caso de prueba 309
        /// </summary>
        public void Aceptar()
        {
            #region Variable Declarations
            WinButton uIAceptarButton = this.UIEjecuciónenloteWindow.UIAceptarWindow.UIAceptarButton;
            #endregion

            // Clic 'Aceptar' botón
            Mouse.Click(uIAceptarButton, new Point(45, 13));
        }
        
        #region Properties
        public UIFlexBusinessERP41HUAWindow UIFlexBusinessERP41HUAWindow
        {
            get
            {
                if ((this.mUIFlexBusinessERP41HUAWindow == null))
                {
                    this.mUIFlexBusinessERP41HUAWindow = new UIFlexBusinessERP41HUAWindow();
                }
                return this.mUIFlexBusinessERP41HUAWindow;
            }
        }
        
        public UIEjecuciónenloteWindow UIEjecuciónenloteWindow
        {
            get
            {
                if ((this.mUIEjecuciónenloteWindow == null))
                {
                    this.mUIEjecuciónenloteWindow = new UIEjecuciónenloteWindow();
                }
                return this.mUIEjecuciónenloteWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIFlexBusinessERP41HUAWindow mUIFlexBusinessERP41HUAWindow;
        
        private UIEjecuciónenloteWindow mUIEjecuciónenloteWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "14.0.23107.0")]
    public class UIFlexBusinessERP41HUAWindow : WinWindow
    {
        
        public UIFlexBusinessERP41HUAWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "FlexBusiness ERP 4.2 - 4110000";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("FlexBusiness ERP 4.2 - 4110000");
            #endregion
        }
        
        #region Properties
        public UIExplorerBarWindow UIExplorerBarWindow
        {
            get
            {
                if ((this.mUIExplorerBarWindow == null))
                {
                    this.mUIExplorerBarWindow = new UIExplorerBarWindow(this);
                }
                return this.mUIExplorerBarWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIOrdenesdecompraAprobWindow UIOrdenesdecompraAprobWindow
        {
            get
            {
                if ((this.mUIOrdenesdecompraAprobWindow == null))
                {
                    this.mUIOrdenesdecompraAprobWindow = new UIOrdenesdecompraAprobWindow(this);
                }
                return this.mUIOrdenesdecompraAprobWindow;
            }
        }
        
        public UI_frmMain_Toolbars_DoToolBar UI_frmMain_Toolbars_DoToolBar
        {
            get
            {
                if ((this.mUI_frmMain_Toolbars_DoToolBar == null))
                {
                    this.mUI_frmMain_Toolbars_DoToolBar = new UI_frmMain_Toolbars_DoToolBar(this);
                }
                return this.mUI_frmMain_Toolbars_DoToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UIExplorerBarWindow mUIExplorerBarWindow;
        
        private UIItemWindow mUIItemWindow;
        
        private UIOrdenesdecompraAprobWindow mUIOrdenesdecompraAprobWindow;
        
        private UI_frmMain_Toolbars_DoToolBar mUI_frmMain_Toolbars_DoToolBar;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "14.0.23107.0")]
    public class UIExplorerBarWindow : WinWindow
    {
        
        public UIExplorerBarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "explorerBar";
            this.WindowTitles.Add("FlexBusiness ERP 4.2 - 4110000");
            #endregion
        }
        
        #region Properties
        public WinButton UICOMPRASButton
        {
            get
            {
                if ((this.mUICOMPRASButton == null))
                {
                    this.mUICOMPRASButton = new WinButton(this);
                    #region Criterio de búsqueda
                    this.mUICOMPRASButton.SearchProperties[WinButton.PropertyNames.Name] = "COMPRAS";
                    this.mUICOMPRASButton.WindowTitles.Add("FlexBusiness ERP 4.2 - 4110000");
                    #endregion
                }
                return this.mUICOMPRASButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICOMPRASButton;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "5";
            this.WindowTitles.Add("FlexBusiness ERP 4.2 - 4110000");
            #endregion
        }
        
        #region Properties
        public UIItemTree UIItemTree
        {
            get
            {
                if ((this.mUIItemTree == null))
                {
                    this.mUIItemTree = new UIItemTree(this);
                }
                return this.mUIItemTree;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTree mUIItemTree;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "14.0.23107.0")]
    public class UIItemTree : WinTree
    {
        
        public UIItemTree(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.WindowTitles.Add("FlexBusiness ERP 4.2 - 4110000");
            #endregion
        }
        
        #region Properties
        public UIOperacionesTreeItem UIOperacionesTreeItem
        {
            get
            {
                if ((this.mUIOperacionesTreeItem == null))
                {
                    this.mUIOperacionesTreeItem = new UIOperacionesTreeItem(this);
                }
                return this.mUIOperacionesTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private UIOperacionesTreeItem mUIOperacionesTreeItem;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "14.0.23107.0")]
    public class UIOperacionesTreeItem : WinTreeItem
    {
        
        public UIOperacionesTreeItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinTreeItem.PropertyNames.Name] = "Operaciones";
            this.SearchProperties["Value"] = "0";
            this.WindowTitles.Add("FlexBusiness ERP 4.2 - 4110000");
            #endregion
        }
        
        #region Properties
        public UIOrdenesdecompraTreeItem UIOrdenesdecompraTreeItem
        {
            get
            {
                if ((this.mUIOrdenesdecompraTreeItem == null))
                {
                    this.mUIOrdenesdecompraTreeItem = new UIOrdenesdecompraTreeItem(this);
                }
                return this.mUIOrdenesdecompraTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private UIOrdenesdecompraTreeItem mUIOrdenesdecompraTreeItem;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "14.0.23107.0")]
    public class UIOrdenesdecompraTreeItem : WinTreeItem
    {
        
        public UIOrdenesdecompraTreeItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinTreeItem.PropertyNames.Name] = "Ordenes de compra";
            this.SearchProperties["Value"] = "1";
            this.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
            this.SearchConfigurations.Add(SearchConfiguration.NextSibling);
            this.WindowTitles.Add("FlexBusiness ERP 4.2 - 4110000");
            #endregion
        }
        
        #region Properties
        public WinTreeItem UIOrdenesdecompraAprobTreeItem
        {
            get
            {
                if ((this.mUIOrdenesdecompraAprobTreeItem == null))
                {
                    this.mUIOrdenesdecompraAprobTreeItem = new WinTreeItem(this);
                    #region Criterio de búsqueda
                    this.mUIOrdenesdecompraAprobTreeItem.SearchProperties[WinTreeItem.PropertyNames.Name] = "Ordenes de compra - Aprobadas";
                    this.mUIOrdenesdecompraAprobTreeItem.SearchProperties["Value"] = "2";
                    this.mUIOrdenesdecompraAprobTreeItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIOrdenesdecompraAprobTreeItem.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIOrdenesdecompraAprobTreeItem.WindowTitles.Add("FlexBusiness ERP 4.2 - 4110000");
                    #endregion
                }
                return this.mUIOrdenesdecompraAprobTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private WinTreeItem mUIOrdenesdecompraAprobTreeItem;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "14.0.23107.0")]
    public class UIOrdenesdecompraAprobWindow : WinWindow
    {
        
        public UIOrdenesdecompraAprobWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "frmVistaAdministrativaListView2";
            this.WindowTitles.Add("FlexBusiness ERP 4.2 - 4110000");
            #endregion
        }
        
        #region Properties
        public UILvItemsList UILvItemsList
        {
            get
            {
                if ((this.mUILvItemsList == null))
                {
                    this.mUILvItemsList = new UILvItemsList(this);
                }
                return this.mUILvItemsList;
            }
        }
        #endregion
        
        #region Fields
        private UILvItemsList mUILvItemsList;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "14.0.23107.0")]
    public class UILvItemsList : WinList
    {
        
        public UILvItemsList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinList.PropertyNames.Name] = "UltraListView1";
            this.WindowTitles.Add("FlexBusiness ERP 4.2 - 4110000");
            #endregion
        }
        
        #region Properties
        public WinListItem UIItem0050009007ListItem
        {
            get
            {
                if ((this.mUIItem0050009007ListItem == null))
                {
                    this.mUIItem0050009007ListItem = new WinListItem(this);
                    #region Criterio de búsqueda
                    this.mUIItem0050009007ListItem.SearchProperties[WinListItem.PropertyNames.Name] = "005-0009007";
                    this.mUIItem0050009007ListItem.WindowTitles.Add("FlexBusiness ERP 4.2 - 4110000");
                    #endregion
                }
                return this.mUIItem0050009007ListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIItem0050009007ListItem;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "14.0.23107.0")]
    public class UI_frmMain_Toolbars_DoToolBar : WinToolBar
    {
        
        public UI_frmMain_Toolbars_DoToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Toolbar";
            this.WindowTitles.Add("FlexBusiness ERP 4.2 - 4110000");
            #endregion
        }
        
        #region Properties
        public WinButton UIAnularlacancelacióndButton
        {
            get
            {
                if ((this.mUIAnularlacancelacióndButton == null))
                {
                    this.mUIAnularlacancelacióndButton = new WinButton(this);
                    #region Criterio de búsqueda
                    this.mUIAnularlacancelacióndButton.SearchProperties[WinButton.PropertyNames.Name] = "Anular la cancelación de comprobante";
                    this.mUIAnularlacancelacióndButton.WindowTitles.Add("FlexBusiness ERP 4.2 - 4110000");
                    #endregion
                }
                return this.mUIAnularlacancelacióndButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIAnularlacancelacióndButton;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "14.0.23107.0")]
    public class UIEjecuciónenloteWindow : WinWindow
    {
        
        public UIEjecuciónenloteWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Ejecución en lote";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Ejecución en lote");
            #endregion
        }
        
        #region Properties
        public UIAceptarWindow UIAceptarWindow
        {
            get
            {
                if ((this.mUIAceptarWindow == null))
                {
                    this.mUIAceptarWindow = new UIAceptarWindow(this);
                }
                return this.mUIAceptarWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIAceptarWindow mUIAceptarWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "14.0.23107.0")]
    public class UIAceptarWindow : WinWindow
    {
        
        public UIAceptarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnAceptar";
            this.WindowTitles.Add("Ejecución en lote");
            #endregion
        }
        
        #region Properties
        public WinButton UIAceptarButton
        {
            get
            {
                if ((this.mUIAceptarButton == null))
                {
                    this.mUIAceptarButton = new WinButton(this);
                    #region Criterio de búsqueda
                    this.mUIAceptarButton.SearchProperties[WinButton.PropertyNames.Name] = "Aceptar";
                    this.mUIAceptarButton.WindowTitles.Add("Ejecución en lote");
                    #endregion
                }
                return this.mUIAceptarButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIAceptarButton;
        #endregion
    }
}
